<a href="https://colab.research.google.com/github/xx290305/Data-Science-Bootcamp/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [388]:
import numpy as np

# ***Tworzenie tablic korzystając z np.array()***

In [389]:
np.__version__

'1.22.4'

In [390]:
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_CopyMode', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__getattr__', '__git_version__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_distributor_in

In [391]:
# help(np.array)

In [392]:
x = np.array([1, 2, 3, 4, 5])
x

array([1, 2, 3, 4, 5])

In [393]:
type(x)

numpy.ndarray

In [394]:
x.shape

(5,)

In [395]:
x.ndim

1

In [396]:
x.size

5

In [397]:
x.dtype

dtype('int64')

In [398]:
y = np.array([1.1, 1.2, 6.7])
y

array([1.1, 1.2, 6.7])

In [399]:
y.dtype

dtype('float64')

In [400]:
z = np.array([[1, 2, 3, 4], [2, 7, 9 ,4]])
print(z, z.shape, z.ndim, z.size)

[[1 2 3 4]
 [2 7 9 4]] (2, 4) 2 8


In [401]:
x = np.array([
              [[1, 2, 3], [4, 5, 6]],
              [[2, 4, 6], [1, 3, 5]]
            ])

In [402]:
x.shape

(2, 2, 3)

In [403]:
y = np.array([1, 2, 3], dtype='complex')

In [404]:
y.dtype

dtype('complex128')

In [405]:
 z = np.array([1.2, 2.9, 3.7], dtype='int')

In [406]:
print(z.dtype, z)

int64 [1 2 3]


In [407]:
z = np.array([True, False], dtype='int')
z

array([1, 0])

# ***Tworzenie pół-gotowych tablic***

In [408]:
x = np.zeros(shape=(10, 4), dtype='int')
x

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [409]:
y = np.ones(shape=(5, 5), dtype='float')
y

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [410]:
z = np.full(shape=(2, 7), fill_value=4, dtype='int')
z

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [411]:
x = np.arange(start=5, stop=21, step=2)
x

array([ 5,  7,  9, 11, 13, 15, 17, 19])

In [412]:
y = np.linspace(start=0, stop=1, num=21)
y

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95, 1.  ])

In [413]:
y.reshape((3, -1))

array([[0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 ],
       [0.35, 0.4 , 0.45, 0.5 , 0.55, 0.6 , 0.65],
       [0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95, 1.  ]])

# ***Operacje na talbicach***

In [414]:
A = np.array([6, 4, 2, 9])
B = np.array([7, 5, 1, 7])

In [415]:
A + B

array([13,  9,  3, 16])

In [416]:
A - B

array([-1, -1,  1,  2])

In [417]:
A * B

array([42, 20,  2, 63])

In [418]:
A /B

array([0.85714286, 0.8       , 2.        , 1.28571429])

In [419]:
A + 16

array([22, 20, 18, 25])

In [420]:
A + B * 3

array([27, 19,  5, 30])

In [421]:
np.add(A, B)

array([13,  9,  3, 16])

In [422]:
np.subtract(A, B)

array([-1, -1,  1,  2])

In [423]:
np.multiply(A, B)

array([42, 20,  2, 63])

In [424]:
np.divide(A, B)

array([0.85714286, 0.8       , 2.        , 1.28571429])

In [425]:
x = np.array([[1, 5], [7, 3]])
y = np.array([[6, 0], [-1, 3]])

print(x, '\n', y)

[[1 5]
 [7 3]] 
 [[ 6  0]
 [-1  3]]


In [426]:
x * y

array([[ 6,  0],
       [-7,  9]])

In [427]:
np.dot(x, y)

array([[ 1, 15],
       [39,  9]])

In [428]:
x @ y

array([[ 1, 15],
       [39,  9]])

# ***Liczby pseudolosowe***

In [429]:
np.random.seed(0)

In [430]:
np.random.randn()

1.764052345967664

In [431]:
np.random.randn(10, 4)

array([[ 0.40015721,  0.97873798,  2.2408932 ,  1.86755799],
       [-0.97727788,  0.95008842, -0.15135721, -0.10321885],
       [ 0.4105985 ,  0.14404357,  1.45427351,  0.76103773],
       [ 0.12167502,  0.44386323,  0.33367433,  1.49407907],
       [-0.20515826,  0.3130677 , -0.85409574, -2.55298982],
       [ 0.6536186 ,  0.8644362 , -0.74216502,  2.26975462],
       [-1.45436567,  0.04575852, -0.18718385,  1.53277921],
       [ 1.46935877,  0.15494743,  0.37816252, -0.88778575],
       [-1.98079647, -0.34791215,  0.15634897,  1.23029068],
       [ 1.20237985, -0.38732682, -0.30230275, -1.04855297]])

In [432]:
np.random.rand(10 ,2)

array([[0.57019677, 0.43860151],
       [0.98837384, 0.10204481],
       [0.20887676, 0.16130952],
       [0.65310833, 0.2532916 ],
       [0.46631077, 0.24442559],
       [0.15896958, 0.11037514],
       [0.65632959, 0.13818295],
       [0.19658236, 0.36872517],
       [0.82099323, 0.09710128],
       [0.83794491, 0.09609841]])

In [433]:
np.random.randint(-67, 10, size=10)

array([-64, -25, -46,   6, -67, -57, -24,  -9, -44,  -8])

In [434]:
np.random.choice([4, 2, 6, 7, 1, 9, 4, 5,])

6

In [435]:
data = np.arange(10)
np.random.shuffle(data)
data

array([0, 1, 4, 8, 5, 7, 3, 6, 2, 9])

# ***Funkcje wbudowane w numpy***

In [436]:
np.exp(1)

2.718281828459045

In [437]:
np.sqrt(9)

3.0

In [438]:
np.all([2, 0 ,6])

False

In [439]:
np.any([1, 0, 0])

True

In [440]:
x = np.random.rand(5)
x

array([0.86510256, 0.50896896, 0.91672295, 0.92115761, 0.08311249])

In [441]:
np.argmax(x)

3

In [442]:
np.argmin(x)

4

In [443]:
np.argsort(x)

array([4, 1, 0, 2, 3])

In [444]:
np.min(x)

0.08311249263060239

In [445]:
np.max(x)

0.9211576102371998

In [446]:
np.mean(x)

0.6590129157719324

In [447]:
np.std(x)

0.32612320754089996

In [448]:
np.median(x)

0.865102561305385

## ***Indeksowanie i wyciananie tablic***

In [449]:
x = np.arange(20)
np.random.shuffle(x)
x

array([10, 18, 16,  1,  5,  7,  4, 17,  9, 15, 12, 13,  6, 14,  0,  3,  2,
       19,  8, 11])

In [450]:
x[np.argmax(x)]

19

In [451]:
x[-5:18]

array([ 3,  2, 19])

In [452]:
x = x.reshape(4, 5)
x

array([[10, 18, 16,  1,  5],
       [ 7,  4, 17,  9, 15],
       [12, 13,  6, 14,  0],
       [ 3,  2, 19,  8, 11]])

In [453]:
x[[1, 3], 3:]

array([[ 9, 15],
       [ 8, 11]])

# ***Iterowanie przez tablicę***

In [454]:
for row in x:
  print(x[:3])

[[10 18 16  1  5]
 [ 7  4 17  9 15]
 [12 13  6 14  0]]
[[10 18 16  1  5]
 [ 7  4 17  9 15]
 [12 13  6 14  0]]
[[10 18 16  1  5]
 [ 7  4 17  9 15]
 [12 13  6 14  0]]
[[10 18 16  1  5]
 [ 7  4 17  9 15]
 [12 13  6 14  0]]


In [455]:
for element in x.ravel():
  print(element)

10
18
16
1
5
7
4
17
9
15
12
13
6
14
0
3
2
19
8
11


In [456]:
x.ravel()

array([10, 18, 16,  1,  5,  7,  4, 17,  9, 15, 12, 13,  6, 14,  0,  3,  2,
       19,  8, 11])

In [457]:
x.flatten()

array([10, 18, 16,  1,  5,  7,  4, 17,  9, 15, 12, 13,  6, 14,  0,  3,  2,
       19,  8, 11])

In [458]:
x

array([[10, 18, 16,  1,  5],
       [ 7,  4, 17,  9, 15],
       [12, 13,  6, 14,  0],
       [ 3,  2, 19,  8, 11]])

In [459]:
x.T

array([[10,  7, 12,  3],
       [18,  4, 13,  2],
       [16, 17,  6, 19],
       [ 1,  9, 14,  8],
       [ 5, 15,  0, 11]])

In [460]:
y = np.arange(start=-8, stop=12, step=0.5).reshape(10, -1)
np.random.shuffle(y)
print(y)

[[-6.  -5.5 -5.  -4.5]
 [ 0.   0.5  1.   1.5]
 [ 2.   2.5  3.   3.5]
 [10.  10.5 11.  11.5]
 [ 4.   4.5  5.   5.5]
 [-2.  -1.5 -1.  -0.5]
 [ 6.   6.5  7.   7.5]
 [ 8.   8.5  9.   9.5]
 [-8.  -7.5 -7.  -6.5]
 [-4.  -3.5 -3.  -2.5]]


In [461]:
y[y > 0]

array([ 0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5, 10. , 10.5, 11. , 11.5,
        4. ,  4.5,  5. ,  5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,
        9.5])

In [462]:
np.bitwise_and(y > -5, y < 5)

array([[False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [False, False, False, False],
       [ True,  True, False, False],
       [ True,  True,  True,  True],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [ True,  True,  True,  True]])

# ***Funkcje statystyczne***

In [463]:
price = np.array([[12.4, 12.7, 12.1, 12.3, 1000],
                  [12.3, 13.1, 11, 11.7, 2000],
                  [11.7, 14.1, 11.6, 14.1, 3000]])

In [464]:
price.sum(axis=0)

array([  36.4,   39.9,   34.7,   38.1, 6000. ])

In [465]:
np.sum(price)

6149.099999999999

In [467]:
np.min(price, axis=0)

array([  11.7,   12.7,   11. ,   11.7, 1000. ])

In [ ]:
np.mean(price, axis=0)