<a href="https://colab.research.google.com/github/xx290305/Data-Science-Bootcamp/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [238]:
import numpy as np

# ***Tworzenie tablic korzystając z np.array()***

In [239]:
np.__version__

'1.22.4'

In [240]:
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_CopyMode', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__getattr__', '__git_version__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_distributor_in

In [241]:
# help(np.array)

In [242]:
x = np.array([1, 2, 3, 4, 5])
x

array([1, 2, 3, 4, 5])

In [243]:
type(x)

numpy.ndarray

In [244]:
x.shape

(5,)

In [245]:
x.ndim

1

In [246]:
x.size

5

In [247]:
x.dtype

dtype('int64')

In [248]:
y = np.array([1.1, 1.2, 6.7])
y

array([1.1, 1.2, 6.7])

In [249]:
y.dtype

dtype('float64')

In [250]:
z = np.array([[1, 2, 3, 4], [2, 7, 9 ,4]])
print(z, z.shape, z.ndim, z.size)

[[1 2 3 4]
 [2 7 9 4]] (2, 4) 2 8


In [251]:
x = np.array([
              [[1, 2, 3], [4, 5, 6]],
              [[2, 4, 6], [1, 3, 5]]
            ])

In [252]:
x.shape

(2, 2, 3)

In [253]:
y = np.array([1, 2, 3], dtype='complex')

In [254]:
y.dtype

dtype('complex128')

In [255]:
 z = np.array([1.2, 2.9, 3.7], dtype='int')

In [256]:
print(z.dtype, z)

int64 [1 2 3]


In [257]:
z = np.array([True, False], dtype='int')
z

array([1, 0])

# ***Tworzenie pół-gotowych tablic***

In [258]:
x = np.zeros(shape=(10, 4), dtype='int')
x

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [259]:
y = np.ones(shape=(5, 5), dtype='float')
y

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [260]:
z = np.full(shape=(2, 7), fill_value=4, dtype='int')
z

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [261]:
x = np.arange(start=5, stop=21, step=2)
x

array([ 5,  7,  9, 11, 13, 15, 17, 19])

In [262]:
y = np.linspace(start=0, stop=1, num=21)
y

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95, 1.  ])

In [263]:
y.reshape((3, -1))

array([[0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 ],
       [0.35, 0.4 , 0.45, 0.5 , 0.55, 0.6 , 0.65],
       [0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95, 1.  ]])

# ***Operacje na talbicach***

In [264]:
A = np.array([6, 4, 2, 9])
B = np.array([7, 5, 1, 7])

In [265]:
A + B

array([13,  9,  3, 16])

In [266]:
A - B

array([-1, -1,  1,  2])

In [267]:
A * B

array([42, 20,  2, 63])

In [268]:
A /B

array([0.85714286, 0.8       , 2.        , 1.28571429])

In [269]:
A + 16

array([22, 20, 18, 25])

In [270]:
A + B * 3

array([27, 19,  5, 30])

In [271]:
np.add(A, B)

array([13,  9,  3, 16])

In [272]:
np.subtract(A, B)

array([-1, -1,  1,  2])

In [273]:
np.multiply(A, B)

array([42, 20,  2, 63])

In [274]:
np.divide(A, B)

array([0.85714286, 0.8       , 2.        , 1.28571429])

In [279]:
x = np.array([[1, 5], [7, 3]])
y = np.array([[6, 0], [-1, 3]])

print(x, '\n', y)

[[1 5]
 [7 3]] 
 [[ 6  0]
 [-1  3]]


In [276]:
x * y

array([[ 6,  0],
       [-7,  9]])

In [281]:
np.dot(x, y)

array([[ 1, 15],
       [39,  9]])

In [282]:
x @ y

array([[ 1, 15],
       [39,  9]])

# ***Liczby pseudolosowe***

In [284]:
np.random.seed(0)

In [283]:
np.random.randn()

-1.0918923098558238

In [287]:
np.random.randn(10, 4)

array([[ 0.14404357,  1.45427351,  0.76103773,  0.12167502],
       [ 0.44386323,  0.33367433,  1.49407907, -0.20515826],
       [ 0.3130677 , -0.85409574, -2.55298982,  0.6536186 ],
       [ 0.8644362 , -0.74216502,  2.26975462, -1.45436567],
       [ 0.04575852, -0.18718385,  1.53277921,  1.46935877],
       [ 0.15494743,  0.37816252, -0.88778575, -1.98079647],
       [-0.34791215,  0.15634897,  1.23029068,  1.20237985],
       [-0.38732682, -0.30230275, -1.04855297, -1.42001794],
       [-1.70627019,  1.9507754 , -0.50965218, -0.4380743 ],
       [-1.25279536,  0.77749036, -1.61389785, -0.21274028]])

In [296]:
np.random.rand(10 ,2)

array([[0.83794491, 0.09609841],
       [0.97645947, 0.4686512 ],
       [0.97676109, 0.60484552],
       [0.73926358, 0.03918779],
       [0.28280696, 0.12019656],
       [0.2961402 , 0.11872772],
       [0.31798318, 0.41426299],
       [0.0641475 , 0.69247212],
       [0.56660145, 0.26538949],
       [0.52324805, 0.09394051]])

In [305]:
np.random.randint(-67, 10, size=10)

array([-13, -67, -29, -48, -21, -25, -11,  -7, -37, -43])

In [306]:
np.random.choice([4, 2, 6, 7, 1, 9, 4, 5,])

9

In [310]:
data = np.arange(10)
np.random.shuffle(data)
data

array([6, 2, 0, 7, 1, 9, 8, 5, 3, 4])

# ***Funkcje wbudowane w numpy***

In [311]:
np.exp(1)

2.718281828459045

In [312]:
np.sqrt(9)

3.0

In [315]:
np.all([2, 0 ,6])

False

In [316]:
np.any([1, 0, 0])

True

In [323]:
x = np.random.rand(5)
x

array([0.13547406, 0.29828233, 0.56996491, 0.59087276, 0.57432525])

In [324]:
np.argmax(x)

3

In [325]:
np.argmin(x)

0

In [326]:
np.argsort(x)

array([0, 1, 2, 4, 3])

In [327]:
np.min(x)

0.13547406422245023

In [328]:
np.max(x)

0.5908727612481732

In [329]:
np.mean(x)

0.4337838621954996

In [330]:
np.std(x)

0.18456623929112265

In [331]:
np.median(x)

0.5699649107012649

## ***Indeksowanie i wyciananie tablic***

In [336]:
x = np.arange(20)
np.random.shuffle(x)
x

array([11,  9,  1, 17,  2,  4,  8, 14,  0,  7,  5, 13, 16,  6, 19, 10, 18,
       15,  3, 12])

In [337]:
x[np.argmax(x)]

19

In [340]:
x[-5:18]

array([10, 18, 15])

In [350]:
x = x.reshape(4, 5)
x

array([[11,  9,  1, 17,  2],
       [ 4,  8, 14,  0,  7],
       [ 5, 13, 16,  6, 19],
       [10, 18, 15,  3, 12]])

In [354]:
x[[1, 3], 3:]

array([[ 0,  7],
       [ 3, 12]])

# ***Iterowanie przez tablicę***

In [ ]:
for row in x:
  print(x[:3])

In [365]:
for element in x.ravel():
  print(element)

11
9
1
17
2
4
8
14
0
7
5
13
16
6
19
10
18
15
3
12


In [358]:
x.ravel()

array([11,  9,  1, 17,  2,  4,  8, 14,  0,  7,  5, 13, 16,  6, 19, 10, 18,
       15,  3, 12])

In [366]:
x.flatten()

array([11,  9,  1, 17,  2,  4,  8, 14,  0,  7,  5, 13, 16,  6, 19, 10, 18,
       15,  3, 12])

In [370]:
x

array([[11,  9,  1, 17,  2],
       [ 4,  8, 14,  0,  7],
       [ 5, 13, 16,  6, 19],
       [10, 18, 15,  3, 12]])

In [369]:
x.T

array([[11,  4,  5, 10],
       [ 9,  8, 13, 18],
       [ 1, 14, 16, 15],
       [17,  0,  6,  3],
       [ 2,  7, 19, 12]])

In [379]:
y = np.arange(start=-8, stop=12, step=0.5).reshape(10, -1)
np.random.shuffle(y)
print(y)

[[-8.  -7.5 -7.  -6.5]
 [ 4.   4.5  5.   5.5]
 [ 2.   2.5  3.   3.5]
 [ 8.   8.5  9.   9.5]
 [-6.  -5.5 -5.  -4.5]
 [-4.  -3.5 -3.  -2.5]
 [10.  10.5 11.  11.5]
 [ 0.   0.5  1.   1.5]
 [ 6.   6.5  7.   7.5]
 [-2.  -1.5 -1.  -0.5]]


In [384]:
y[y > 0]

array([ 4. ,  4.5,  5. ,  5.5,  2. ,  2.5,  3. ,  3.5,  8. ,  8.5,  9. ,
        9.5, 10. , 10.5, 11. , 11.5,  0.5,  1. ,  1.5,  6. ,  6.5,  7. ,
        7.5])

In [382]:
np.bitwise_and(y > -5, y < 5)

array([[False, False, False, False],
       [ True,  True, False, False],
       [ True,  True,  True,  True],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [False, False, False, False],
       [ True,  True,  True,  True],
       [False, False, False, False],
       [ True,  True,  True,  True]])